# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

#language: R
#sudo: false
#cache: packages

# Run Travis CI for R using  https://eddelbuettel.github.io/r-travis/
# Edit: Run Travis CI for R using https://swihart.github.io/r-travis/
language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs https://swihart.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) r-cran-pinp
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-inline r-cran-pinp libgsl0-dev r-cran-runit r-cran-optimx r-cran-bridgedist r-cran-stabledist r-cran-libstabler

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
