# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
    - libgsl0ldbl
    - libgsl0-dev
    #- libgsl2
    #- gsl-bin
